// <auto-generated />
using System;
using CopelinSystem.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CopelinSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216025831_AddAppBranding")]
    partial class AddAppBranding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CopelinSystem.Models.AppBranding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FooterHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("footer_html");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.HasKey("Id");

                    b.ToTable("app_branding");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FooterHtml = "<footer class=\"main-footer\">\n    <strong> {{Year}} <a href=\"#\">Estimating Module | Copelin System</a> - </strong>\n    Qld Governement - QBuild.\n    <div class=\"float-right d-none d-sm-inline-block\">\n        <b>Version</b> {{Version}}\n    </div>\n</footer>",
                            IsLocked = true
                        });
                });

            modelBuilder.Entity("CopelinSystem.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ClientCode");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ClientName");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DateCreated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("RegionId");

                    b.HasKey("ClientId");

                    b.HasIndex("RegionId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.ClientContact", b =>
                {
                    b.Property<int>("ClientContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClientContactId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientContactId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientId");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ContactEmail");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ContactName");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ContactPhone");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DateCreated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsPrimary");

                    b.HasKey("ClientContactId");

                    b.HasIndex("ClientId");

                    b.ToTable("client_contacts", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.Consultant", b =>
                {
                    b.Property<int>("ConsultantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConsultantId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultantId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Address");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BusinessName");

                    b.Property<string>("Contact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Contact");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DateCreated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Phone");

                    b.Property<string>("Services")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Services");

                    b.Property<string>("SupplierNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SupplierNumber");

                    b.HasKey("ConsultantId");

                    b.ToTable("consultants", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.Contractor", b =>
                {
                    b.Property<int>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContractorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractorId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Address");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BusinessName");

                    b.Property<string>("Contact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Contact");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DateCreated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Phone");

                    b.Property<string>("Services")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Services");

                    b.Property<string>("SupplierNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SupplierNumber");

                    b.HasKey("ContractorId");

                    b.ToTable("contractors", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DateCreated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FullName");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("RegionId");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RegionId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeRoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeRoleId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("RoleType")
                        .HasColumnType("int")
                        .HasColumnName("RoleType");

                    b.HasKey("EmployeeRoleId");

                    b.HasIndex("EmployeeId", "RoleType")
                        .IsUnique();

                    b.ToTable("employee_roles", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.HelpArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HelpSectionId")
                        .HasColumnType("int");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("HelpSectionId");

                    b.ToTable("HelpArticles");
                });

            modelBuilder.Entity("CopelinSystem.Models.HelpSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("HelpSections");
                });

            modelBuilder.Entity("CopelinSystem.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PermissionName");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.ProjectEmail", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EmailBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailBody");

                    b.Property<string>("EmailBodyHtml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailBodyHtml");

                    b.Property<string>("EmailFrom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EmailFrom");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("EmailSubject");

                    b.Property<string>("EmailTo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EmailTo");

                    b.Property<bool>("IsMatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMatched");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ProcessedDate");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectId");

                    b.Property<string>("ProjectWr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectWr");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ReceivedDate");

                    b.HasKey("EmailId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_emails", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.ProjectEmailAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttachmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ContentType");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EmailId")
                        .HasColumnType("int")
                        .HasColumnName("EmailId");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FileName");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FilePath");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("FileSize");

                    b.HasKey("AttachmentId");

                    b.HasIndex("EmailId");

                    b.ToTable("project_email_attachments", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.ProjectList", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ProjectActualPrice")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ProjectActualPrice");

                    b.Property<string>("ProjectClient")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectClient");

                    b.Property<DateTime>("ProjectClientCompletion")
                        .HasColumnType("date")
                        .HasColumnName("ProjectClientCompletion");

                    b.Property<DateTime>("ProjectClientRequired")
                        .HasColumnType("date")
                        .HasColumnName("ProjectClientRequired");

                    b.Property<DateTime?>("ProjectComplete")
                        .HasColumnType("date")
                        .HasColumnName("ProjectComplete");

                    b.Property<string>("ProjectComponentisation")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("ProjectComponentisation");

                    b.Property<string>("ProjectConsultant")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectConsultant");

                    b.Property<string>("ProjectContact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectContact");

                    b.Property<string>("ProjectContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectContactEmail");

                    b.Property<string>("ProjectContractor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectContractor");

                    b.Property<DateTime>("ProjectDateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ProjectDateCreated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectDescription");

                    b.Property<string>("ProjectEllipesStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectEllipesStatus");

                    b.Property<DateTime?>("ProjectEndDate")
                        .HasColumnType("date")
                        .HasColumnName("ProjectEndDate");

                    b.Property<DateTime?>("ProjectEstEval")
                        .HasColumnType("date")
                        .HasColumnName("ProjectEstEval");

                    b.Property<string>("ProjectEtenderNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectEtenderNo");

                    b.Property<string>("ProjectFeeprop")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectFeeprop");

                    b.Property<string>("ProjectFolderPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectFolderPath");

                    b.Property<string>("ProjectIndicative")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectIndicative");

                    b.Property<string>("ProjectIrisNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectIrisNo");

                    b.Property<string>("ProjectLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectLocation");

                    b.Property<int?>("ProjectManagerID")
                        .HasColumnType("int")
                        .HasColumnName("ProjectManagerID");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProjectName");

                    b.Property<string>("ProjectOneSchool")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ProjectOneSchool");

                    b.Property<string>("ProjectProgramCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectProgramCode");

                    b.Property<string>("ProjectPurchaseOrder")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectPurchaseOrder");

                    b.Property<string>("ProjectQuoteTracker")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProjectQuoteTracker");

                    b.Property<string>("ProjectRegion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectRegion");

                    b.Property<string>("ProjectReqOrder")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProjectReqOrder");

                    b.Property<string>("ProjectSeniorEstimator")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectSeniorEstimator");

                    b.Property<DateTime?>("ProjectStartDate")
                        .HasColumnType("date")
                        .HasColumnName("ProjectStartDate");

                    b.Property<byte?>("ProjectStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("ProjectStatus");

                    b.Property<string>("ProjectSupervisor")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ProjectSupervisor");

                    b.Property<DateTime?>("ProjectTendered")
                        .HasColumnType("date")
                        .HasColumnName("ProjectTendered");

                    b.Property<string>("ProjectUserIds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectUserIds");

                    b.Property<string>("ProjectWicNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectWicNo");

                    b.Property<string>("ProjectWo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ProjectWo");

                    b.Property<string>("ProjectWorkstype")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectWorkstype");

                    b.Property<string>("ProjectWr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectWr");

                    b.Property<DateTime?>("ProjectWrRequested")
                        .HasColumnType("date")
                        .HasColumnName("ProjectWrRequested");

                    b.HasKey("ProjectId");

                    b.ToTable("project_list", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RegionName");

                    b.HasKey("RegionId");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolePermissionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<bool>("IsGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsGranted");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint")
                        .HasColumnName("RoleId");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.TaskConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsValueBased")
                        .HasColumnType("bit");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ValueThresholds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("task_configurations", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.TaskList", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DateCreated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateEnded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DateEnded")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Dependencies")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Dependencies");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int?>("EstimatedDays")
                        .HasColumnType("int")
                        .HasColumnName("EstimatedDays");

                    b.Property<int?>("Progress")
                        .HasColumnType("int")
                        .HasColumnName("Progress");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("Status");

                    b.Property<string>("Task")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Task");

                    b.Property<int?>("TaskProjectId")
                        .HasColumnType("int")
                        .HasColumnName("TaskProjectId");

                    b.HasKey("TaskId");

                    b.HasIndex("TaskProjectId");

                    b.ToTable("task_list", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AdDomain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AdDomain");

                    b.Property<string>("AdSid")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AdSid");

                    b.Property<string>("AdUsername")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AdUsername");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Avatar");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DateCreated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<string>("Firstname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Firstname");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("datetime")
                        .HasColumnName("LastActive");

                    b.Property<string>("Lastname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Lastname");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Region");

                    b.Property<byte>("UserType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("UserType")
                        .HasComment("1=ReadOnly, 2=Estimator, 3=Manager, 4=PrincipalEstimator, 5=Admin");

                    b.HasKey("UserId");

                    b.HasIndex("AdSid")
                        .HasFilter("[AdSid] IS NOT NULL");

                    b.HasIndex("AdUsername")
                        .IsUnique()
                        .HasFilter("[AdUsername] IS NOT NULL");

                    b.HasIndex("Region");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.UserProductivity", b =>
                {
                    b.Property<int>("ProductivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductivityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductivityId"));

                    b.Property<string>("ProductivityComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductivityComment");

                    b.Property<DateTime?>("ProductivityDate")
                        .HasColumnType("date")
                        .HasColumnName("ProductivityDate");

                    b.Property<DateTime>("ProductivityDateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ProductivityDateCreated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<TimeSpan?>("ProductivityEndTime")
                        .HasColumnType("time")
                        .HasColumnName("ProductivityEndTime");

                    b.Property<int?>("ProductivityProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProductivityProjectId");

                    b.Property<TimeSpan?>("ProductivityStartTime")
                        .HasColumnType("time")
                        .HasColumnName("ProductivityStartTime");

                    b.Property<string>("ProductivitySubject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProductivitySubject");

                    b.Property<int?>("ProductivityTaskId")
                        .HasColumnType("int")
                        .HasColumnName("ProductivityTaskId");

                    b.Property<float?>("ProductivityTimeRendered")
                        .HasColumnType("real")
                        .HasColumnName("ProductivityTimeRendered");

                    b.Property<int?>("ProductivityUserId")
                        .HasColumnType("int")
                        .HasColumnName("ProductivityUserId");

                    b.HasKey("ProductivityId");

                    b.HasIndex("ProductivityProjectId");

                    b.HasIndex("ProductivityTaskId");

                    b.ToTable("user_productivity", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.UserProjectPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId")
                        .IsUnique();

                    b.ToTable("user_project_preference", (string)null);
                });

            modelBuilder.Entity("CopelinSystem.Models.Client", b =>
                {
                    b.HasOne("CopelinSystem.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CopelinSystem.Models.ClientContact", b =>
                {
                    b.HasOne("CopelinSystem.Models.Client", "Client")
                        .WithMany("ClientContacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CopelinSystem.Models.Employee", b =>
                {
                    b.HasOne("CopelinSystem.Models.Region", "Region")
                        .WithMany("Employees")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CopelinSystem.Models.EmployeeRole", b =>
                {
                    b.HasOne("CopelinSystem.Models.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CopelinSystem.Models.HelpArticle", b =>
                {
                    b.HasOne("CopelinSystem.Models.HelpSection", "HelpSection")
                        .WithMany("Articles")
                        .HasForeignKey("HelpSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HelpSection");
                });

            modelBuilder.Entity("CopelinSystem.Models.ProjectEmail", b =>
                {
                    b.HasOne("CopelinSystem.Models.ProjectList", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CopelinSystem.Models.ProjectEmailAttachment", b =>
                {
                    b.HasOne("CopelinSystem.Models.ProjectEmail", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("CopelinSystem.Models.RolePermission", b =>
                {
                    b.HasOne("CopelinSystem.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("CopelinSystem.Models.TaskConfiguration", b =>
                {
                    b.HasOne("CopelinSystem.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CopelinSystem.Models.TaskList", b =>
                {
                    b.HasOne("CopelinSystem.Models.ProjectList", "Project")
                        .WithMany()
                        .HasForeignKey("TaskProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CopelinSystem.Models.UserProductivity", b =>
                {
                    b.HasOne("CopelinSystem.Models.ProjectList", "Project")
                        .WithMany()
                        .HasForeignKey("ProductivityProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CopelinSystem.Models.TaskList", "Task")
                        .WithMany()
                        .HasForeignKey("ProductivityTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CopelinSystem.Models.UserProjectPreference", b =>
                {
                    b.HasOne("CopelinSystem.Models.ProjectList", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopelinSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CopelinSystem.Models.Client", b =>
                {
                    b.Navigation("ClientContacts");
                });

            modelBuilder.Entity("CopelinSystem.Models.Employee", b =>
                {
                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("CopelinSystem.Models.HelpSection", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("CopelinSystem.Models.Region", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
